rosbag record --tcpnodelay \
/drone_0_odom_visualization/robot \
/drone_0_odom_visualization/path \
/drone_1_odom_visualization/robot \
/drone_1_odom_visualization/path \
/drone_2_odom_visualization/robot \
/drone_2_odom_visualization/path \
/drone_3_odom_visualization/robot \
/drone_3_odom_visualization/path \
/drone_4_odom_visualization/robot \
/drone_4_odom_visualization/path \
/drone_5_odom_visualization/robot \
/drone_5_odom_visualization/path \
/drone_6_odom_visualization/robot \
/drone_6_odom_visualization/path \
/drone_7_odom_visualization/robot \
/drone_7_odom_visualization/path \
/drone_8_odom_visualization/robot \
/drone_8_odom_visualization/path \
/drone_9_odom_visualization/robot \
/drone_9_odom_visualization/path \
/drone_10_odom_visualization/robot \
/drone_10_odom_visualization/path \
/drone_11_odom_visualization/robot \
/drone_11_odom_visualization/path \
/drone_12_odom_visualization/robot \
/drone_12_odom_visualization/path \
/drone_13_odom_visualization/robot \
/drone_13_odom_visualization/path \
/drone_14_odom_visualization/robot \
/drone_14_odom_visualization/path \
/drone_15_odom_visualization/robot \
/drone_15_odom_visualization/path \
/drone_16_odom_visualization/robot \
/drone_16_odom_visualization/path \
/drone_17_odom_visualization/robot \
/drone_17_odom_visualization/path \
/drone_18_odom_visualization/robot \
/drone_18_odom_visualization/path \
/drone_19_odom_visualization/robot \
/drone_19_odom_visualization/path \
/drone_20_odom_visualization/robot \
/drone_20_odom_visualization/path \
/drone_21_odom_visualization/robot \
/drone_21_odom_visualization/path \
/drone_22_odom_visualization/robot \
/drone_22_odom_visualization/path \
/drone_23_odom_visualization/robot \
/drone_23_odom_visualization/path \
/drone_24_odom_visualization/robot \
/drone_24_odom_visualization/path \
/drone_25_odom_visualization/robot \
/drone_25_odom_visualization/path \
/drone_26_odom_visualization/robot \
/drone_26_odom_visualization/path \
/drone_27_odom_visualization/robot \
/drone_27_odom_visualization/path \
/drone_28_odom_visualization/robot \
/drone_28_odom_visualization/path \
/drone_29_odom_visualization/robot \
/drone_29_odom_visualization/path \
/drone_30_odom_visualization/robot \
/drone_30_odom_visualization/path \
/drone_31_odom_visualization/robot \
/drone_31_odom_visualization/path \
/drone_32_odom_visualization/robot \
/drone_32_odom_visualization/path \
/drone_33_odom_visualization/robot \
/drone_33_odom_visualization/path \
/drone_34_odom_visualization/robot \
/drone_34_odom_visualization/path \
/drone_35_odom_visualization/robot \
/drone_35_odom_visualization/path \
/drone_36_odom_visualization/robot \
/drone_36_odom_visualization/path \
/drone_37_odom_visualization/robot \
/drone_37_odom_visualization/path \
/drone_38_odom_visualization/robot \
/drone_38_odom_visualization/path \
/drone_39_odom_visualization/robot \
/drone_39_odom_visualization/path \
/drone_40_odom_visualization/robot \
/drone_40_odom_visualization/path \
/drone_41_odom_visualization/robot \
/drone_41_odom_visualization/path \
/drone_42_odom_visualization/robot \
/drone_42_odom_visualization/path \
/drone_43_odom_visualization/robot \
/drone_43_odom_visualization/path \
/drone_44_odom_visualization/robot \
/drone_44_odom_visualization/path \
/drone_45_odom_visualization/robot \
/drone_45_odom_visualization/path \
/drone_46_odom_visualization/robot \
/drone_46_odom_visualization/path \
/drone_47_odom_visualization/robot \
/drone_47_odom_visualization/path \
/drone_48_odom_visualization/robot \
/drone_48_odom_visualization/path \
/drone_49_odom_visualization/robot \
/drone_49_odom_visualization/path \
/map_generator/global_cloud